GET http://localhost:2137/games?pageNumber=1&pageSize=10

###

GET http://localhost:2137/games/2

###

POST http://localhost:2137/games
Content-Type: application/json

{
    "name": "Super Mario Bros. Wonder",
    "genreId": 3,
    "price": 59.99,
    "releaseDate": "2023-10-20",
    "publisherId": 1
}

###

POST http://localhost:2137/games
Content-Type: application/json

{
    "name": "Street Fighter II",
    "genreIds": [1],
    "price": 9.99,
    "releaseDate": "1991-02-01",
    "publisherId": 2
}

###

POST http://localhost:2137/games
Content-Type: application/json

{
    "name": "Test Game",
    "genreId": 1,
    "price": 9.99,
    "releaseDate": "1991-02-01"
}

###

PUT http://localhost:2137/games/2
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreIds": [1],
    "price": 19.99,
    "releaseDate": "1992-07-15",
    "publisherId": 2
}

###

DELETE http://localhost:2137/games/3

###

GET http://localhost:2137/genres

